apiVersion: apps/v1
kind: Deployment
metadata:
  name: vx-mind-mapper-ui
  namespace: varhavix
  labels:
    app: vx-mind-mapper-ui
    tier: ui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vx-mind-mapper-ui
  template:
    metadata:
      labels:
        app: vx-mind-mapper-ui
        tier: ui
    spec:
      containers:
        - name: vx-mind-mapper-ui
          image: varhavix/vx-mind-mapper-ui:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: vx-mind-mapper-ui
  namespace: varhavix
spec:
  selector:
    app: vx-mind-mapper-ui
  ports:
    - port: 80
      targetPort: 80
