# Multi-stage Dockerfile for Angular 21+ Landing UI
FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build -- --configuration production

FROM nginx:1.25-alpine
COPY --from=builder /app/dist/varhavix-lms-angular/browser /usr/share/nginx/html
COPY ../vx_infra_foundation/docker/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
